############################# Default configuration ########################
title = "misael gaytan | designer / developer"
# post pagination
paginate = "6"
#post excerpt
summaryLength = "10"
# disqus short name
#disqusShortname = "agico" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
